### ISSUE TITLE
Unable to build solution in latest VS 2017

### ISSUE THREAD

**Issue by StefH** [GitTools/GitReleaseNotes#113]
When building, I get this error message:

> 1>------ Build started: Project: GitReleaseNotes, Configuration: Debug Any CPU ------
> 1>    Fody (version 1.28.3.0) Executing
> 1>MSBUILD : error : Fody: An unhandled exception occurred:
> 1>MSBUILD : error : Exception:
> 1>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 1>MSBUILD : error : StackTrace:
> 1>MSBUILD : error : 
> 1>MSBUILD : error : Server stack trace: 
> 1>MSBUILD : error :    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
> 1>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
> 1>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.GetParameters()
> 1>MSBUILD : error :    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> 1>MSBUILD : error : 
> 1>MSBUILD : error : Exception rethrown at [0]: 
> 1>MSBUILD : error :    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
> 1>MSBUILD : error :    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
> 1>MSBUILD : error :    at IInnerWeaver.set_Logger(ILogger value)
> 1>MSBUILD : error :    at Processor.ExecuteInOwnAppDomain() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 146
> 1>MSBUILD : error :    at Processor.Inner() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 93
> 1>MSBUILD : error :    at Processor.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 45
> 1>MSBUILD : error : Source:
> 1>MSBUILD : error : mscorlib
> 1>MSBUILD : error : TargetSite:
> 1>MSBUILD : error : Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
> 1>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 1>MSBUILD : error : StackTrace:
> 1>MSBUILD : error : 
> 1>MSBUILD : error : 
> 1>      Finished Fody 208ms.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Note when I upgrade `Fody` and `Costura.Fody` to latest versions, I can build.

**Comment by StefH** [comment]
Above error is solved.

Now I get a new one:

> The "Fody.WeavingTask" task was not given a value for the required parameter "IntermediateDir".

Upgrading Fody to `Fody.1.29.4` solved this. I'll create a PR?
