### ISSUE TITLE
Error generating release notes from BitBucket private repo

### ISSUE THREAD

**Issue by DevlinSchoonraad** [GitTools/GitReleaseNotes#71]
When using BitBucket, calling "GitReleaseNotes.exe /OutputFile ReleaseNotes.md /username <username> /password <password>" generates the following error. There is a closed issue under issues for the repository.

Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'RestSharp.JsonObject' does not contain a definition for 'issues'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at GitReleaseNotes.IssueTrackers.BitBucket.BitBucketApi.GetClosedIssues(GitReleaseNotesArguments arguments, Nullable`1 since, String accountName, String repoSlug, Boolean oauth) in c:\Users\Jake\_code\GitReleaseNotes\src\GitReleaseNotes\IssueTrackers\BitBucket\BitBucketApi.cs:line 35
   at GitReleaseNotes.IssueTrackers.BitBucket.BitBucketIssueTracker.GetClosedIssues(Nullable`1 since) in c:\Users\Jake\_code\GitReleaseNotes\src\GitReleaseNotes\IssueTrackers\BitBucket\BitBucketIssueTracker.cs:line 88
   at GitReleaseNotes.ReleaseNotesGenerator.GenerateReleaseNotes(IRepository gitRepo, IIssueTracker issueTracker, SemanticReleaseNotes previousReleaseNotes, String[] categories, TaggedCommit tagToStartFrom, ReleaseInfo currentReleaseInfo, String diffUrlFormat) in c:\Users\Jake\_code\GitReleaseNotes\src\GitReleaseNotes\ReleaseNotesGenerator.cs:line 22
   at GitReleaseNotes.Program.GenerateReleaseNotes(String[] args) in c:\Users\Jake\_code\GitReleaseNotes\src\GitReleaseNotes\Program.cs:line 114
   at GitReleaseNotes.Program.Main(String[] args) in c:\Users\Jake\_code\GitReleaseNotes\src\GitReleaseNotes\Program.cs:line 30

**Comment by DevlinSchoonraad** [comment]
I found the /ConsumerKey and /ConsumerSecretKey switches in the help, but these too failed with the same "Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'RestSharp.JsonObject' does not contain a definition for 'issues'" error. I made changes to the code to get this working.

**Comment by GeertvanHorrik** [comment]
I have switched to Atlassian SDK for jira. Maybe that supports bitbucket as well.

**Comment by DevlinSchoonraad** [comment]
Hi Geert

I fixed this and the pull request https://github.com/GitTools/GitReleaseNotes/pull/72 has been merged. Is there an issue with the change?

**Comment by GeertvanHorrik** [comment]
Nope, if it's merged, we can close this. Thanks for the update!

**Comment by DevlinSchoonraad** [comment]
No problem
