### ISSUE TITLE
Better exception when ordinal parameter is not used

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitReleaseNotes#91]
Unhandled Exception: System.InvalidOperationException: Number of ordinal arguments must at least {0}.
   at Args.ModelBindingDefinition`1.EnsureCorrectNumberOfOrdinalArguments(IEnumerable`1 ordinalArgs)
   at Args.ModelBindingDefinition`1.BindModel(TModel model, IEnumerable`1 args)
   at Args.ModelBindingDefinition`1.CreateAndBind(IEnumerable`1 args)
   at GitReleaseNotes.Program.Main(String[] args) in C:\projects\gitreleasenotes\src\GitReleaseNotes\Program.cs:line 32

**Comment by giggio** [comment]
:+1: 
Same problem here.

**Comment by giggio** [comment]
Ok, you have to do `GitReleaseNotes.exe . /OutputFile ReleaseNotes.md`. The dot is the secret, it is the working directory. If you run `GitReleaseNotes.exe /?` you will see the options.
The docs are not correct, they do not mention that. And the app should not throw an exception, it should say what is missing.
I suggest docopt .net to make that easier and follow standards.

**Comment by pardahlman** [comment]
Same problem for me.
