### ISSUE TITLE
GitReleaseNotes.exe /OutputFile CHANGELOG.md throws exception

### ISSUE THREAD

**Issue by mrbelk** [GitTools/GitReleaseNotes#95]
When I try to run this command from within my repo, I get the following error:

```
Unhandled Exception: System.InvalidOperationException: Number of ordinal arguments must at least {0}.
   at Args.ModelBindingDefinition`1.EnsureCorrectNumberOfOrdinalArguments(IEnumerable`1 ordinalArgs)
   at Args.ModelBindingDefinition`1.BindModel(TModel model, IEnumerable`1 args)
   at Args.ModelBindingDefinition`1.CreateAndBind(IEnumerable`1 args)
   at GitReleaseNotes.Program.Main(String[] args) in C:\projects\gitreleasenotes\src\GitReleaseNotes\Program.cs:line 32
```
When I try to run the tool specifying the WorkingDirectory (of "."), I get nothing.  When I specify /Verbose, I can't find where a logfile might be created and there is no verbose logging emitted to the console (Powershell).

What might I be doing wrong?

**Comment by JakeGinnivan** [comment]
Try

Gitreleasenotes . /o changelog.md

Sent from my Windows Phone
________________________________

**Comment by mrbelk** [comment]
no joy.  Same error.

**Comment by xpicio** [comment]
Hello i have the same issue with version 0.7.1 installed by chocolatey.

The command ```Gitreleasenotes /O test.md``` it does generate the following exception:
                                                                                                                 
```Unhandled Exception: System.InvalidOperationException: Number of ordinal arguments must at least {0}.            
   at Args.ModelBindingDefinition`1.EnsureCorrectNumberOfOrdinalArguments(IEnumerable`1 ordinalArgs)             
   at Args.ModelBindingDefinition`1.BindModel(TModel model, IEnumerable`1 args)                                  
   at Args.ModelBindingDefinition`1.CreateAndBind(IEnumerable`1 args)                                            
   at GitReleaseNotes.Program.Main(String[] args) in C:\projects\gitreleasenotes\src\GitReleaseNotes\Program.cs:line 32```

The command ```Gitreleasenotes . /O test.md``` it does not generate any error but no file is created.

**Comment by mrbelk** [comment]
Any movement on this issue?  Would really like to use this tool for building ReleaseNotes.  The GitVersion stuff is great, and this would be a nice companion for that.

**Comment by dennisdoomen** [comment]
I installed mine using Chocolatey, and it worked for the first time (although the tags were not ordered correctly) using ` gitreleasenotes . /o notes.md /alltags /verbose`. However, after deleting the output file and re-running the command-line, nothing happens. No exception, no nothing. Had the same thing the last time I tried this project.

**Comment by dazinator** [comment]
I haven't tried replicating this yet, but perhaps your working directory is not what you believe it to be? Can you try, rather than a ".", specify the full path to some location and then check for the file there

**Comment by dennisdoomen** [comment]
![image](https://cloud.githubusercontent.com/assets/572734/12866475/c1d595b4-ccce-11e5-877b-a2c1c4f4af5b.png)

The first time it works, the next time nothing happens. As if it is keeping some state somewhere.

**Comment by JakeGinnivan** [comment]
A while back a bunch of stuff got broken, at the moment I am just using `gitreleasenotes . /o newrelease.md`.

Because it work enough for me I haven't got back to it :(

**Comment by mkoertgen** [comment]
Had the same exception as in https://github.com/GitTools/GitReleaseNotes/issues/95#issue-111035509. 

Adding "." as working directory worked for me

**Comment by dennisdoomen** [comment]
The point is that it doesn't throw anything. It just doesn't work anymore.

**Comment by GeertvanHorrik** [comment]
Once GitTools.Core is stable enough, we will give this component some love again.

**Comment by dennisdoomen** [comment]
:+1:

**Comment by aateeque** [comment]
This is caused by the first argument being a switch (arg preceded by `/`). First argument must always be the `WorkingDirectory` path because of the `ArgsMemberSwitch` attribute on https://github.com/GitTools/GitReleaseNotes/blob/master/src/GitReleaseNotes/GitReleaseNotesArguments.cs#L11

**Comment by pkiers** [comment]
Hello,
I've heard you were looking for that stuff for  a long time, so I finally found it for you, read more here <http://desire.construction-consulting.com/e2yyck>

Thanks for your consideration, p.kiers@home.nl
