### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitReleaseNotes#96]
I have been using an older version of GitReleaseNotes Command Line tool for a while, thought I would try out the latest [version on NuGet](https://www.nuget.org/packages/GitReleaseNotes/)

I am calling out to it during a Team City build. It ran fine the first build! The second build it has started throwing this exception.

Perhaps this is something I have configured wrong, but not obvious from the log output what that is..

Here is the log output:

```
 C:\TeamCity\buildAgent\work\2a00c132b39aee80\src\packages\GitReleaseNotes\tools\GitReleaseNotes.exe /RepoUsername Dazinator /RepoPassword ******* /RepoUrl https://github.com/dazinator/Xamarin.TestyDroid.git /Token ******* /OutputFile ReleaseNotes.md /Version 0.1.1+1 /WorkingDirectory C:\TeamCity\buildAgent\work\2a00c132b39aee80
[12:44:25][Step 2/3] in directory: C:\TeamCity\buildAgent\work\2a00c132b39aee80
[12:44:25][Step 2/3] Cloning a git repo from https://github.com/dazinator/Xamarin.TestyDroid.git
[12:44:25][Step 2/3] Deleting existing .git folder from 'C:\TeamCity\buildAgent\work\2a00c132b39aee80\.git' to force new checkout from url
[12:44:25][Step 2/3] Retrieving git info from url 'https://github.com/dazinator/Xamarin.TestyDroid.git';
[12:44:27][Step 2/3] One remote found (origin -> 'https://github.com/dazinator/Xamarin.TestyDroid.git';).
[12:44:27][Step 2/3] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
[12:44:27][Step 2/3] Skipping local branch creation since it already exists 'refs/remotes/origin/master'.
[12:44:27][Step 2/3] HEAD points at branch 'refs/heads/master'.
[12:44:27][Step 2/3] Switching to branch 'master'
[12:44:27][Step 2/3] Checking out files that might be needed later.
[12:44:27][Step 2/3]   Trying to check out 'ReleaseNotes.md'
[12:44:27][Step 2/3] 
[12:44:27][Step 2/3] Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
[12:44:27][Step 2/3]    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
[12:44:27][Step 2/3]    at GitReleaseNotes.Git.GitRepositoryInfoFinder.GetLastTaggedCommit(IRepository gitRepo, Func`2 filterTags)
[12:44:27][Step 2/3]    at GitReleaseNotes.Git.GitRepositoryInfoFinder.GetTag(IRepository gitRepo, String fromTag)
[12:44:27][Step 2/3]    at GitReleaseNotes.Git.GitRepositoryInfoFinder.GetLastTaggedCommit(IRepository gitRepo)
[12:44:27][Step 2/3]    at GitReleaseNotes.Program.GenerateReleaseNotes(String[] args)
[12:44:27][Step 2/3]    at GitReleaseNotes.Program.Main(String[] args)
[12:44:27][Step 2/3] Process exited with code 255
```

**Comment by dazinator** [comment]
Noticed there was an erroneous TAG created after the last release (created in error). Deleting this tag fixed the problem.

The issue was, I have a couple of different build configurations in team city chained to the same dependency. One does VCS labelling, and publishes a github release (using git release notes etc)

The second does a NuGet release (publish).

This second one also had VCS labelling switched on, and so was creating this additional tag on the repo whenever I published to NuGet. This would then cause the next GitHub release fail as GitReleaseNotes hits the above issue.

**Comment by dazinator** [comment]
Closing as I found the solution to this
